spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.show-sql=false

jwt.secret=${JWT_SECRET}
# location of the uploaded files for local development is `uploads` - define it in .env.properties
storage.upload-path=${STORAGE_UPLOAD_PATH}

# Password reset
app.mail.from=noreply@mail.idemudia.dev
app.resend.api-key=${RESEND_API_KEY}
app.frontend.url=${FRONTEND_URL}
app.password-reset.token-ttl-minutes=30